env: "dev"
clients:
  auth:
      address: auth-service:44044
      timeout: 5s
      retriesCount: 10
  inventory:
      address: inventory-service:44045
      timeout: 5s
      retriesCount: 10
  order:
       address : order-service:44046
       timeout: 5s
       retriesCount: 10
  jaeger:
       address: jaeger:14268