env: "local"
clients:
  auth:
      address: localhost:44044
      timeout: 5s
      retriesCount: 10
  inventory:
      address: localhost:44045
      timeout: 5s
      retriesCount: 10
  order:
       address : localhost:44046
       timeout: 5s
       retriesCount: 10